# Generated by Django 3.1.7 on 2021-05-24 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50, verbose_name='内容')),
                ('year', models.CharField(max_length=4, verbose_name='年')),
                ('month', models.CharField(max_length=2, verbose_name='月')),
                ('day', models.CharField(max_length=2, verbose_name='日')),
                ('time', models.CharField(max_length=2, verbose_name='時間')),
                ('minutes', models.CharField(max_length=2, verbose_name='分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='表示名')),
                ('start', models.TimeField(verbose_name='開始時間')),
                ('end', models.TimeField(verbose_name='終了時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('unique_name', models.CharField(max_length=12, null=True, verbose_name='会員ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID')),
            ],
        ),
    ]
